version: "3"

services:
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      #POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports: 
      - "5433:5432"

  api:
    build: 
      context: ./
      dockerfile: Dockerfile-Python
    environment:
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped
    ports: 
      - "80:5000"   
    depends_on:
      - db
